# render.yaml

services:
    - type: web
      name: discord-bot
      runtime: python  # typ środowiska uruchomieniowego
  version: 3.11.5  # wymagana wersja Pythona
  installCommand:  # komendy instalacyjne
    "apt-get update && apt-get install -y ffmpeg libopus0 opus-tools && pip install -r requirements.txt"
      startCommand: python main.py
      envVars:
        - key: DISCORD_TOKEN
          value: your_discord_token_here
        - key: VOICE_CHANNEL_ID
          value: your_channel_id_here
        - key: ALLOWED_GUILD_IDS
          value: "server_id1,server_id2"  # ID serwerów rozdzielone przecinkami
        - key: TZ
          value: Europe/Warsaw
        - key: PORT
          value: 8080
      healthCheckPath: /
